### ISSUE TITLE
Connection unexpectedly failed: Unexpected exception while connecting to socket

### ISSUE THREAD

**Issue by raucao** [dgarage/NBXplorer#400]
Since yesterday (apparently at block height 774627), I'm getting the same error as in #170, but with the problem and solution therein definitely not applying to my setup.

I had been running NBXplorer for BTCPayServer for years now, and when this exception first appeared it was on version `2.2.20`. So the first thing I tried was upgrading to `2.3.58`, and subsequently upgrading bitcoind from `23.0` to `24.0.1`. However, the exception persists and it's unable keep a connection open to bitcoind apparently. The full log looks like this:

```plain
info: Configuration:  BTC: Full node version detected: 240001
info: Configuration:  BTC: Node banlist loaded
info: Configuration:  BTC: Loading chain from cache...
info: Configuration:  BTC: Height: 774835
info: Configuration:  BTC: Trying to connect via the P2P protocol to trusted node (127.0.0.1:8333)...
info: Explorer:       BTC: TCP Connection succeed, handshaking...
info: Explorer:       BTC: Handshaked
info: Configuration:  BTC: Loading chain from node
info: Explorer:       BTC: Loading chain...
info: Explorer:       BTC: Chain loaded
info: Explorer:       BTC: NBXplorer is correctly whitelisted by the node
info: Configuration:  BTC: Height: 774836
info: Configuration:  BTC: Saving chain to cache...
info: Configuration:  BTC: Chain cached
info: Explorer:       BTC: Handshaked node
info: Explorer:       BTC: Starting scan at block 774627
info: Events:         BTC: Node state changed: NotStarted => NBXplorerSynching
fail: Explorer:       BTC: Connection unexpectedly failed: Unexpected exception while connecting to socket
info: Events:         BTC: Node state changed: NBXplorerSynching => NotStarted
info: Configuration:  BTC: Testing RPC connection to http://127.0.0.1:8332/
fail: Explorer:       BTC: Unhandled error in IndexBlockLoop
fail: Explorer:       System.OperationCanceledException: The peer has been disconnected
         at NBXplorer.BlockDownloader.DownloadBlocks(BlockLocator fork, CancellationToken cancellationToken)+MoveNext() in /opt/nbxplorer/NBXplorer/BlockDownloader.cs:line 57
         at NBXplorer.BlockDownloader.DownloadBlocks(BlockLocator fork, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at NBXplorer.ExplorerBehavior.IndexBlockLoop(Node node, CancellationToken cancellationToken) in /opt/nbxplorer/NBXplorer/ExplorerBehavior.cs:line 319
         at NBXplorer.ExplorerBehavior.IndexBlockLoop(Node node, CancellationToken cancellationToken) in /opt/nbxplorer/NBXplorer/ExplorerBehavior.cs:line 319
info: Configuration:  BTC: RPC connection successful
info: Configuration:  BTC: Full node version detected: 240001
info: Configuration:  BTC: Loading chain from cache...
```

**Comment by raucao** [comment]
Anyone has any ideas for how I could debug this further to fix our production BTCPay instance?

**Comment by konigra** [comment]
I do too, get this error:

Feb 06 13:36:50 raspberrypi dotnet[16093]: warn: NBXplorer.Indexer.BTC: Node disconnected for reason: **Unexpected exception while connecting to socket (Specified argument was out of the range of valid values. (Parameter 'Array size too big'))**

Feb 06 13:36:50 raspberrypi dotnet[16093]: info: NBXplorer.Events: BTC: Node state changed: NBXplorerSynching => NotStarted

**Comment by the-smooth-operator** [comment]
we are also experiencing this issue on our production instance.
Is there a workaround for letting NBXplorer move on? Can we somehow skip that block?

**Comment by konigra** [comment]
hey @the-smooth-operator ,
NBXplorer fixed it, and it is already in the latest BTCPAYSERVER version 1.7.5. .
An update to the latest version worked for me just fine.

**Comment by raucao** [comment]
I see only one commit in master since the version that is failing, and it's only changing a test: b0b7e98cb98a4eacdebf5872a8ebc404f47133a9

**Comment by NicolasDorier** [comment]
Hi @raucao, sorry for coming back late. In general this error happen when you pruned too much your node.

NBXplorer got stuck on a block, then your node continued to sync. When NBXplorer get unstuck, your node pruned the block it needs.

**Comment by NicolasDorier** [comment]
A workaround this problem

Should be to run the following command on the database, assuming you use btcpay:

```bash
docker exec -ti generated_postgres_1 psql -U postgres -d nbxplorermainnet -c "DELETE FROM nbxv1_settings WHERE code='BTC' AND key='BlockLocator-';"
```
Then restart nbxplorer. However, some blocks won't be parsed so I hope nothing happened then.

**Comment by NicolasDorier** [comment]
@konigra is another issue unrelated to your issue. A block was crashing versions from NBX that was older than november 14.

**Comment by NicolasDorier** [comment]
@raucao I think knowing why it does this. I believe it is caused by the indexer running a `mempool` request when connecting to your node. Because the mempool is full it overload the node with messages.

I can remove this probably. But would you be open to instead change the backend from DBTrie to Postgres? It doesn't have this problem and there is an easy way to migrate.

**Comment by NicolasDorier** [comment]
Also you can try `v2.3.60` that I just pushed, that may solve your issue.

**Comment by raucao** [comment]
`2.3.60` didn't fix it for me. But migrating to Postgres worked.

Thanks. :pray:
