### ISSUE TITLE
Can't process block 896727

### ISSUE THREAD

**Issue by turbolay** [dgarage/NBXplorer#518]
Nbx (latest) can't process block 896727, probably because of those transactions:
749fdc72f1c99398899425253875deb1d7e5e040db14014ea57db71c610dad26
fccbed4e54a7983984f9cf422fa88210267e9d7187565f8d840f91787442a951

I don't have more details for now

**Comment by wille** [comment]
Stack trace

```
 2025-05-14T21:27:16Z UpdateTip: new best=00000000000000000001b121672a1fb75b6f820748cdc4a01899116c161d2b05 height=896727 version=0x2510c000 log2_work=95.608498 tx=1190364490 date='2025-05-14T21:28:30Z' progress=1.000000 cache=2006.5MiB(12668955txo)

May 14 23:27:17.027 nbxplorer [40m[32minfo[39m[22m[49m: NBXplorer.Indexer.BTC: Node disconnected (Unexpected exception while connecting to socket)
May 14 23:27:17.037 nbxplorer [40m[32minfo[39m[22m[49m: NBXplorer.Events: BTC: Node state changed: Ready => NotStarted
May 14 23:27:17.061 nbxplorer [41m[30mfail[39m[22m[49m: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 20 seconds
May 14 23:27:17.061 nbxplorer System.OperationCanceledException: The peer has been disconnected
May 14 23:27:17.061 nbxplorer at NBXplorer.Backend.Indexer.AskNextHeaders(Node node, CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 382
May 14 23:27:17.061 nbxplorer at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 215
May 14 23:27:17.061 nbxplorer at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 220
May 14 23:27:17.061 nbxplorer at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 148
May 14 23:27:17.061 nbxplorer at NBXplorer.Backend.Indexer.IndexerLoop() in /source/NBXplorer/Backend/Indexer.cs:line 95
```

**Comment by sutt0n** [comment]
can confirm, also receiving this issue

**Comment by ts506** [comment]
Same here, multiple btcpayserver versions including: v2.1.1+6b5cab65a  v2.0.6+ba8feeddd v1.11.3+08b6942c5

**Comment by turbolay** [comment]
Seems like an issue in NBitcoin, here's Wasabi's StackTrace:

```
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'Array size too big')
   at NBitcoin.Protocol.VarString.StaticRead(BitcoinStream bs, Byte[]& bytes)
   at NBitcoin.BitcoinStream.ReadWrite(Script& script)
   at NBitcoin.TxIn.ReadWrite(BitcoinStream stream)
   at NBitcoin.BitcoinStream.ReadWrite(TxInList& list)
   at NBitcoin.Transaction.ReadWrite(BitcoinStream stream)
   at NBitcoin.BitcoinStream.ReadWrite[T](T& data)
   at NBitcoin.BitcoinStream.ReadWrite[T](List`1& list)
   at NBitcoin.Block.ReadWrite(BitcoinStream stream)
   at NBitcoin.Block.Parse(String hex, ConsensusFactory consensusFactory)
   at NBitcoin.RPC.RPCClient.GetBlockAsync(uint256 blockId, CancellationToken cancellationToken)
```

**Comment by NicolasDorier** [comment]
on it

**Comment by ts506** [comment]
For your information, this issue is impacting Azure deployments as well.

**Comment by rockstardev** [comment]
Thanks to everyone that's sending in logs, we're reviewing and should have fix for the problem shortly <3

**Comment by rockstardev** [comment]
Conversation on @NicolasDorier X (https://x.com/NicolasDorier/status/1922799602727633395) points out that this is related to the transaction https://mempool.space/tx/889d4fed1ec4a775d02082b5ff727f48d93013469db709d8d435e15b173118f3

Probably a problem with the version number (425,699,129), we'll post more details as we get them.

**Comment by wille** [comment]
Just mentioning that I noticed that nbx 2.5.25 doesn't print a stack trace and is not waiting between retries, 2.5.23 did

**Comment by Roasbeef** [comment]
Not super familiar with the codebase, but looks like it's hitting the limit when trying to read an additional input from a transaction in the block: https://github.com/MetacoSA/NBitcoin/blob/7c01c452c2dd455a1752b870c9b6c059d6c2d35a/NBitcoin/BitcoinStream.cs#L298-L299

**Comment by Roasbeef** [comment]
Prospective patch is up now: https://github.com/MetacoSA/NBitcoin/pull/1269

Looks like a carry over from an earlier version of the OG segwit implementation.

**Comment by rockstardev** [comment]
@Roasbeef looking at details I think it's combo problem, both what you linked + Segwit serialization flag fix that Nicolas is working in PR

**Comment by NicolasDorier** [comment]
Fixed NBXplorer: 2.5.26, NBitcoin: 8.0.12

**Comment by yilakb** [comment]
Is anyone else still experiencing the NBXplorerSynching => NotStarted loop after hitting block height 896746? is the fix in

**Comment by yilakb** [comment]
ok it works now

**Comment by rockstardev** [comment]
Works for me on one instance: 

![Image](https://github.com/user-attachments/assets/791b428c-2882-4cee-a054-a38253a2491b)

**Comment by sutt0n** [comment]
working here on btcpayserver 1.13.7 🎉

**Comment by lukechilds** [comment]
Tested and working on latest Umbrel App Store version, great work lads 🫡

**Comment by kallerosenbaum** [comment]
Confirming that the fix works for us! Thanks!
